### ISSUE TITLE
Interaction between pref and shared preferences

### ISSUE THREAD

**Issue by jonmountjoy** [DavBfr/flutter_pref#13]
Hello!

I don't understand the interaction between this package and the shared preferences package, which backs it.  In particular, I am having trouble getting them to sync, as can be demonstrated by this code:

```
PrefSwitch(
                title: Text('Allow Cramming'),
                pref: "isCrammingAllowed",
                onChange: (v) async {
                  var prefService = PrefService.of(context);
                  print(prefService.get("isCrammingAllowed"));
                  SharedPreferences prefsn = await SharedPreferences.getInstance();
                  print(prefsn.getBool("isCrammingAllowed"));
                },
              ),
```

I would expect `v` and `prefService.get()` and `SharedPreferences.getBool()` all to have the same value.

But they don't.  The `SharedPreferences` value is not the same. 

It puzzles me as I can see pref does call SharedPreferences here: https://github.com/DavBfr/flutter_pref/blob/8cb07bc056ea5c074c8d7391f1190224c4a6c34f/pref/lib/src/service/shared_preferences.dart#L37

But somehow that change isn't reflected in the `onChange` or elsewhere. 

Does anyone know what's happening here?

Thanks!

**Comment by MrCsabaToth** [comment]
An important note: when you initalize pref then you can specify a prefix. I specify one, so if I'd try to read the "raw" preferences without that prefix through SharedPreferences I'd either not get anything or some dormant value.
Question: is the `onChange` called before, after, or along with (there can be race conditions due to async nature) the `sharedPreferences.setBool`? Actually I'd be happy if I can access the older value (preferably through the pref API).

**Comment by DavBfr** [comment]
The change is happening, but the example app uses `PrefServiceCache` which won't store anything permanently: only in-memory storage.

onChange is called after storing the new value. You're right, there is no way to get the old value at this point. What API would you purpose?

**Comment by MrCsabaToth** [comment]
`PrefServiceCache` means that this is not a bug? @jonmountjoy was trying to look for something in the physical shared pref where the value was untouched due to the cache service?

The old value is not a need for me, I just tried to look for a positive spin on the issue. So don't bother with it. One day it could be parameter of the onChange, but I would not bother until need emerges.

**Comment by DavBfr** [comment]
I think that's it.
